### ISSUE TITLE
wgsl: Validate recursion disallowed

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1467]
* [X] Recursive function call (#2817)
* [X] Recursive structs (#2825)
* [X] Recursive type alias (#2823)
* [X] Recursive const initializer (#2835)
* [X] Recursive override initializer (#2835)

**Comment by dneto0** [comment]
Also, check initializers among objects declared at module scope.
See expected changes due to https://github.com/gpuweb/gpuweb/issues/3081

E.g. 
const-depends-on-const
override-depends-on-override

**Comment by jrprice** [comment]
All completed now.
