### ISSUE TITLE
wgsl: Validation module scoped variables

### ISSUE THREAD

**Issue by dj2** [gpuweb/cts#1570]
* [X] `var<function>` at module scope is disallowed (#3347)
* [X] `var` without an address space at module scope that is not `texture` or `sampler` fails (#3338)
* [X] `var` for a `texture` or `sampler` with an address space is disallowed (#3338)
* [X] `var` for a `texture` or `sampler` without an address space passes (#3338)
* [X] `var` for `private`, `workgroup`, `uniform` or `storage` with declarations matching store types acceptable (#3338)
* [X] `var` for `private`, `workgroup`, `uniform` or `storage` with declarations with invalid store types (#3338)
* [X] `var<uniform>` with non-host-shareable type fails (#3338)
* [X] `var<uniform>` with non-constructable type fails (#3338)
* [X] `var<uniform>` with constructable, host-shareable type passes (#3338)
* [X] `var<storage>` with non-hostshareable type fails (#3338)
* [X] `var<storage>` with host-shareable but not constructable type passes (#3338)
* [x] `var<storage>` with `read` and `read-write` access passes (#2824)
* [x] `var<storage>` with `write` access fails (#2824)
* [X] `uniform`, `storage`, `texture` and `sampler` `var`s with `group` and `binding` passes (#3348)
* [X] `uniform`, `storage`, `texture` and `sampler` `var`s with `group` and without `binding` fails (#3348)
* [X] `uniform`, `storage`, `texture` and `sampler` `var`s without `group` and with `binding` fails (#3348)
* [X] `uniform`, `storage`, `texture` and `sampler` `var`s without `group` and `binding` fails (#3348)
