### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/cts#3]
(i.e. to-do list)

## Short term

- [x] add [license](https://github.com/gpuweb/admin)
- [x] delete dawn-node code for now
- [x] probably delete suites/demos
- [x] try to clean up the mess of interfaces/typedefs that are all over the place, esp naming/terminology
  - [x] document them
  - [x] document params interfaces
- [x] add presubmit to make sure imports end in `.js`
- [x] move JS from .html to .ts files so it can be checked

## Medium term

- [x] write high-level documentation (in particular about test queries and test expectations)
- [x] write more comprehensive documentation with examples of writing tests, etc.
- [x] comment code more
- [x] any TODOs in the code
- [x] check whether cts works on Windows (may have path issues during build)
- [x] update @webgpu/types to match current idl
  - [ ] fill out package.json fields
  - [x] update again later
  - [x] and (probably) delete framework/gpu/dummy.ts
- [x] shaderc (glslang?)
  - [x] fix https://github.com/kainino0x/-webgpu-shaderc/issues/1
  - [x] figure out how to package .wasm instead of base64 (or maybe both)
  - [x] fix missing error messages and crash on 310 es
  - [x] publish a smaller build
  - [ ] fill out package.json fields
- [x] sort spec listings (index.js) before generating so they don't get random orders every time
- [x] implement per-platform test expectations and skips
  - [x] ~add negative queries (`?q=abc:&not=abc:{}` or something)~
  - [x] write code to take a list of sub-group queries + full list of groups and produce a complete list of queries which splits each group into parts
    - (allows for each part to have different expectations)
  - [x] generate `<meta name="variant">` list from that
  - [ ] make TestExpectations understand GPU-related tags
  - [x] hook it up with [TestExpectations](https://chromium.googlesource.com/chromium/src/+/master/third_party/blink/web_tests/TestExpectations)
  - [x] get chrome to run these tests via wpt (but only on gpu bots)
    - [chromium docs](https://chromium.googlesource.com/chromium/src/+/master/docs/testing/web_platform_tests.md)
- [x] do we need to be able to disable tests inside the harness? (probably not?) no
- [x] (possibly) change results json format to use query strings instead of nesting?
- [x] add values that get passed into t.params but are not part of the case name #66 
- [x] ~allow parameterizations that aren't just number/string/boolean? Probably should do this by adding a parameterizer which takes a js dictionary, uses the keys for case naming, and passes the values into the test function~
- [x] make standalone runner generate a fully nested tree #73
- [x] run tests on workers #79

## Longer term

- [ ] improve standalone runner (Vue? + better styling)

## Maybe consider someday

- [x] make testing on node+dawn work for real
- [ ] maybe?? go semi-buildless by adding a service worker that compiles typescript on the fly

**Comment by Kangz** [comment]
It means the Conformance Test Suite and will be the test suite for WebGPU.
